In [1]:
import torch
import regex as re
import pandas as pd
import torch.nn.functional as F
import matplotlib.pyplot as plt

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [4]:
companies = pd.read_csv('../data/companies_sorted.csv')

KeyboardInterrupt: 

In [7]:
companies = companies['name'].astype(str).tolist()

NameError: name 'companies' is not defined

In [8]:
companies = [company.strip() for company in companies if re.fullmatch(r"[A-Za-z]+", company) and company.upper() == company.strip().upper()]

NameError: name 'companies' is not defined

In [9]:
N = torch.zeros((27, 27), dtype=torch.int32).to(device)

In [10]:
chars = sorted(list(set(''.join(companies))))

stoi = {s : i + 1 for i, s in enumerate(chars)}
stoi['.'] = 0


itos = {i:s for s, i in stoi.items()}

NameError: name 'companies' is not defined

In [ ]:
for c in companies:
    chs = ['.'] + list(c) + ['.']
    
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1

In [6]:
P = (N+1).float()
P /= P.sum(1, keepdim=True)

NameError: name 'N' is not defined

In [5]:
P

NameError: name 'P' is not defined

In [52]:
N

tensor([[    0, 60090, 40307, 59166, 32007, 37989, 28739, 25497, 20875, 38716,
          9184, 18517, 24671, 50201, 23621, 17535, 43985,  5249, 25351, 72564,
         42708, 10164, 20093, 20503,  3184,  5252,  6769],
        [67615,  6354, 17526, 30321, 25083,  4035,  9395, 16214,  3239, 15868,
          1591,  9443, 52782, 26347, 59994,  1449, 21465,  1858, 68271, 34478,
         42600,  9497, 11538,  4276,  5332, 10486,  4888],
        [10732, 17242,  2488,  2101,  1035, 19185,   530,   552,   666, 18671,
           363,   364, 10580,  1185,   674, 16762,   874,   104, 12745,  4923,
          1324,  8501,   450,   476,   180,  2759,   336],
        [22589, 34356,   999,  4969,  1058, 25988,   855,   787, 34230, 15469,
           188, 13269, 11122,  1945,  1916, 57144,  1488,   327, 13152,  7776,
         16422,  8143,   673,   496,   339,  3296,   216],
        [27709, 18111,  2320,  3294,  3314, 41095,  1729,  3258,  1529, 34376,
           519,   662,  2757,  3062,  1347, 14638,  1

In [53]:
g = torch.Generator(device=device).manual_seed(2147483647)

for i in range(20):
  ix = 0
  out = []
  while True:

    p = P[ix]

    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    if ix == 0:
      break
  print(''.join(out))

kued.
wp.
stingorsubgomb.
masturamsct.
mpexotrkafrenerdexenoilu.
prmagechindinger.
o.
dos.
crayfilterisosostoudtstette.
santsm.
mplyatannuponfy.
c.
deltes.
blmind.
malana.
s.
m.
c.
gers.
ckeavene.


In [46]:
log_likelihood = 0.0
n = 0

for c in ['kued']:
    chs = ['.'] + list(c) + ['.']
    
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1
        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
        print(f'{ch1} {ch2} : {prob:.4f} : {logprob:.4f} : {log_likelihood:.4f}')

. k : 0.0249 : -3.6919 : -3.6919
k u : 0.0281 : -3.5724 : -7.2643
u e : 0.0427 : -3.1530 : -10.4173
e d : 0.0488 : -3.0205 : -13.4379
d . : 0.1401 : -1.9655 : -15.4034


In [48]:
nll = -log_likelihood
nll/n

tensor(3.0807, device='cuda:0')

In [49]:
xs = []
ys = []

In [11]:
for c in companies[:1]:
    chs = ['.'] + list(c) + ['.']

    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]

        xs.append(ix1)
        ys.append(ix2)
xs = torch.tensor(xs).to(device)
ys = torch.tensor(ys).to(device)

NameError: name 'companies' is not defined

In [54]:
xenc = F.one_hot(xs, num_classes=27).float()

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]], device='cuda:0')

In [57]:
w = torch.randn((27, 27)).to(device)
logits = xenc @ w

tensor([[-1.6334, -1.5020,  0.5424, -0.0684, -0.7714, -0.9059, -1.0847,  1.0578,
          0.6474, -0.5017, -0.2253, -0.6355, -0.9692,  1.0109, -0.8164, -0.4861,
         -0.3888,  0.2530, -0.7587, -1.3482, -1.0147,  0.4977, -0.1788,  0.7779,
          1.5528,  0.2492,  1.3121],
        [ 0.3653,  0.6433,  2.1455,  0.0173,  0.1377, -1.1649, -0.4289, -1.0201,
          0.5782,  1.2906,  0.5696,  0.6741,  1.6338,  1.8709, -0.4921,  0.7787,
         -0.8105,  0.5894,  0.7626, -0.6522, -0.5814, -1.5895, -0.9866, -0.0789,
          2.1246, -0.5395, -0.2312],
        [ 0.7498, -0.6273, -0.0223, -0.1982,  0.0962, -1.1757, -1.9116, -0.1000,
          0.3447,  0.2949,  1.0709, -0.8476, -0.4123,  0.6040,  0.5357,  2.0758,
          0.5220, -0.0572, -0.3699, -0.4986, -0.5333,  1.5824,  0.8138,  0.1055,
         -1.1127, -0.0227, -0.0094],
        [-0.3966,  0.7808, -0.7469, -1.3443, -0.8718,  0.4477,  0.4375, -0.3912,
          0.6792, -1.1678,  0.2552,  0.0312, -0.4837, -0.5654,  0.2383,  2.3786

In [63]:
counts = logits.exp()
prob = counts / counts.sum(1, keepdims=True)

In [ ]:
g = torch.Generator(device=device).manual_seed(2147483647)

In [68]:
W = torch.randn((27, 27), generator=g, requires_grad=True, device=device)

In [74]:
xenc = F.one_hot(xs, num_classes=27).float()
logits = xenc @ W
counts = logits.exp()
probs = counts / counts.sum(1, keepdims=True)
loss = -probs[torch.arange(4), ys].log().mean()

In [75]:
probs.shape

torch.Size([4, 27])

In [78]:
nlls = torch.zeros(4)
for i in range(4):
    x = xs[i].item()
    y = ys[i].item()
    print('--------')
    print(f'bigram example {i+1}: {itos[x]}{itos[y]} (indexes {x},{y})')
    print('input to the neural net:', x)
    print('output probabilities from the neural net:', probs[i])
    print('label (actual next character):', y)
    p = probs[i, y]
    print('probability assigned by the net to the the correct character:', p.item())
    logp = torch.log(p)
    print('log likelihood:', logp.item())
    nll = -logp
    print('negative log likelihood:', nll.item())
    nlls[i] = nll

    print('=========')
    print('average negative log likelihood, i.e. loss =', nlls.mean().item())

--------
bigram example 1: .i (indexes 0,9)
input to the neural net: 0
output probabilities from the neural net: tensor([0.0479, 0.0394, 0.0062, 0.0128, 0.0320, 0.0040, 0.0216, 0.0169, 0.0105,
        0.0245, 0.0036, 0.2807, 0.0605, 0.0451, 0.0084, 0.0192, 0.0101, 0.0568,
        0.0045, 0.1067, 0.0118, 0.0228, 0.0884, 0.0103, 0.0194, 0.0322, 0.0038],
       device='cuda:0', grad_fn=<SelectBackward0>)
label (actual next character): 9
probability assigned by the net to the the correct character: 0.024479953572154045
log likelihood: -3.7099008560180664
negative log likelihood: 3.7099008560180664
average negative log likelihood, i.e. loss = 0.9274752140045166
--------
bigram example 2: ib (indexes 9,2)
input to the neural net: 9
output probabilities from the neural net: tensor([0.0213, 0.0641, 0.0166, 0.0174, 0.0061, 0.0173, 0.0036, 0.0010, 0.0687,
        0.1070, 0.0658, 0.0278, 0.0299, 0.0148, 0.0621, 0.0219, 0.0123, 0.0100,
        0.0336, 0.0088, 0.0356, 0.0241, 0.0800, 0.0110, 0.0175

In [82]:
loss = -probs[torch.arange(4), ys].log().mean()

In [88]:
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27, 27), generator=g, requires_grad=True).to(device)

In [90]:
# forward pass
xenc = F.one_hot(xs, num_classes=27).float() # input to the network: one-hot encoding
logits = xenc @ W # predict log-counts
counts = logits.exp() # counts, equivalent to N
probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
loss = -probs[torch.arange(4), ys].log().mean()

In [91]:
# backward pass
W.grad = None # set grad to zero
loss.backward()

In [92]:
W.grad

C:\Users\Ihor\AppData\Local\Temp\ipykernel_1668\1614539626.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:494.)
  W.grad


In [3]:
W.data += -0.1 * W.grad

NameError: name 'W' is not defined

In [9]:
N = torch.zeros((27, 27), dtype=torch.int32).to(device)

In [15]:
chars = sorted(list(set(''.join(companies))))

stoi = {s : i + 1 for i, s in enumerate(chars)}
stoi['.'] = 0

itos = {s : i for i, s in stoi.items()}

In [19]:
for c in companies:
    chs = ['.'] + list(c) + ['.']

    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]

        N[ix1, ix2] += 1

In [20]:
N

tensor([[    0, 60090, 40307, 59166, 32007, 37989, 28739, 25497, 20875, 38716,
          9184, 18517, 24671, 50201, 23621, 17535, 43985,  5249, 25351, 72564,
         42708, 10164, 20093, 20503,  3184,  5252,  6769],
        [67615,  6354, 17526, 30321, 25083,  4035,  9395, 16214,  3239, 15868,
          1591,  9443, 52782, 26347, 59994,  1449, 21465,  1858, 68271, 34478,
         42600,  9497, 11538,  4276,  5332, 10486,  4888],
        [10732, 17242,  2488,  2101,  1035, 19185,   530,   552,   666, 18671,
           363,   364, 10580,  1185,   674, 16762,   874,   104, 12745,  4923,
          1324,  8501,   450,   476,   180,  2759,   336],
        [22589, 34356,   999,  4969,  1058, 25988,   855,   787, 34230, 15469,
           188, 13269, 11122,  1945,  1916, 57144,  1488,   327, 13152,  7776,
         16422,  8143,   673,   496,   339,  3296,   216],
        [27709, 18111,  2320,  3294,  3314, 41095,  1729,  3258,  1529, 34376,
           519,   662,  2757,  3062,  1347, 14638,  1

In [26]:
p = N[0].float()
P = p / p.sum()

tensor([0.0000, 0.0809, 0.0543, 0.0796, 0.0431, 0.0511, 0.0387, 0.0343, 0.0281,
        0.0521, 0.0124, 0.0249, 0.0332, 0.0676, 0.0318, 0.0236, 0.0592, 0.0071,
        0.0341, 0.0977, 0.0575, 0.0137, 0.0270, 0.0276, 0.0043, 0.0071, 0.0091],
       device='cuda:0')

In [48]:
g = torch.Generator(device=device).manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
ix

11

In [2]:
chars = sorted(list(set(''.join(companies))))

stoi = {s : i + 1 for i, s in enumerate(chars)}
stoi['.'] = 0


itos = {i:s for s, i in stoi.items()}

NameError: name 'companies' is not defined